title: HeartbeatChimes
description: Music from your heartbeat
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme 
relative_links:
  enabled: true
  collections: true
logo: assets/img/logo.png
